---
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present

- name: Ensure Apache is enabled and running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Configure index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify:
    - Restart Apache

- name: Open port 80 on Ubuntu (ufw)
  ansible.builtin.ufw:
    rule: allow
    port: 80
    proto: tcp
  when: ansible_facts['os_family'] == "Debian"