---
- name: Install&Enable tuned
  hosts: all
  become: true
  tasks:
    - name: Install tuned package
      package:
        name: tuned
        state: present

    - name: Ensure tuned is running
      service:
        name: tuned
        state: started
        enabled: true