---
- name: Update MOTD
  hosts: all
  become: true
  tasks:
    - name: Get the IP address of the host
      command: hostname -I
      register: ip_output

    - name: Get the hostname of the host
      command: hostname
      register: hostname_output

    - name: Update the motd file
      copy:
        content: |
          Welcome to your system!
          Hostname: {{ hostname_output.stdout }}
          IP Address: {{ ip_output.stdout }}
          Отличного дня, Админ!
        dest: /etc/motd